warehouse = 'ARRHYTHMIA_STUDY'
warehouse_optimized = 'ARRHYTHMIA_STUDY_OPTIMIZED'
database = 'ARRHYTHMIA_STUDY'
schema = 'ARRHYTHMIA_STUDY'

# account = 'zt97901.eu-west-3.aws'
# user = 'xandervr'
# password = 'Xandervr1'
# role = 'SYSADMIN'

account = 'cm60646.eu-west-3.aws'
user = 'Demo'
password = 'SnowflakeDemo1'
role = 'SYSADMIN'

csv_stage = 'STAGE_CSV'
csv_stage_lead = 'STAGE_CSV_LEAD'
functions_stage = 'STAGE_FUNCTIONS'
models_stage = 'STAGE_MODELS'

csv_format = 'FORMAT_CSV'

fact_patient = 'FACT_PATIENT'
dim_disease = 'DIM_DISEASE'
dim_disease_info = 'DIM_DISEASE_INFO'
dim_lead = 'DIM_LEAD'
table_user = 'USER'
table_patient_user = 'PATIENT_USER'
table_tensions_diseases = 'TENSION_DISEASE'
table_model_labels = 'MODEL_LABEL'
