name: Generate JSON file from CodeQL query

on:
  push:
    branches: [ main ]  # Set the branch you want to trigger the action on

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'python'

      - name: Generate JSON file
        run: |
          codeql database create mydatabase --language=python .  # Replace 'python' with your desired language
          codeql query run /path/to/your/query.ql --database=mydatabase --output=json > results.json  # Replace '/path/to/your/query.ql' with the path to your query

      - name: Upload JSON file
        uses: actions/upload-artifact@v2
        with:
          name: CodeQL query results
          path: results.json
