name: CodeQL Analysis 2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
      
      - name: Autobuild changed libraries
        uses: github/codeql-action/autobuild@v2
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          # Set the path to the custom queries
          queries: ./.github/codeql/custom-queries
          # Set the path to the downloaded codeql database
          database: ${{ github.workspace }}/db
          # Set the path to the results directory
          results-path: ${{ github.workspace }}/results
      
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: ${{ github.workspace }}/results
