[theme]

# Primary accent for interactive elements
primaryColor = '#5BC0EB'

# Background color for the main content area
backgroundColor = '#49535a'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#222222'

# Color used for almost all text
textColor = '#F7F3E3'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"

[snowflake]
user = "xxx"
password = "xxx"
account = "xxx"
warehouse = "xxx"
database = "xxx"
schema = "xxx"